-- AIMSC_DEV 이력 테이블 8개 — 파티션 + 로컬 인덱스 재구축  ** 실제 변경이 일어난다 **
--
-- 실행:
--   docker exec -it tibero7_ut_tablename bash -lc \
--     'cd /tmp/tbmig && tbsql aimsc_dev/aimsc_dev @15_aimsc_hist_rebuild.sql'
--
-- 반드시 14_aimsc_precheck.sql 을 먼저 돌려 확인 항목이 모두 0건인지 볼 것.
--
-- === 왜 재구축인가 ===
--   Oracle 호환 DB 는 이미 만들어진 일반 테이블을 제자리에서 파티션 테이블로
--   바꾸지 못한다. 그래서 데이터를 백업 테이블로 옮기고, 원본을 지우고,
--   파티션 정의로 다시 만든 뒤 되넣는다.
--
--   RENAME 방식을 쓰지 않은 이유: 테이블 이름만 바뀌고 PK 인덱스 이름
--   (PK_T_ITSE_*)은 옛 테이블에 그대로 남아, 새 테이블에 같은 이름을 못 쓴다.
--   CREATE TABLE ... AS SELECT 는 데이터만 복사하므로 이름 충돌이 없다.
--
-- === 이 스크립트가 바꾸는 것 ===
--   1. PK 가 복합키가 된다 — (기존PK컬럼, 파티션키)
--      로컬 유니크 인덱스는 파티션 키를 반드시 포함해야 한다. 이것이
--      "Global 이 아니라 Local Index" 요구를 만족시키는 유일한 방법이다.
--      => 기존 PK 컬럼 단독 유일성은 이제 DB 가 보장하지 않는다.
--
--   2. 파티션 키 컬럼이 NOT NULL 이 된다 (아래 목록)
--      PK 컬럼은 NULL 을 가질 수 없다. 실측(2026-08-18) 시점에 해당 컬럼의
--      NULL 은 0건이었으나, ** 앞으로 앱이 NULL 을 넣으면 INSERT 가 실패한다. **
--        T_ITSE_AI_DRF_DGNST01L     AI_DGNST_DTTM
--        T_ITSE_AI_MODL_OP01L       MNTG_STRT_DTTM
--        T_ITSE_AI_MVPCT_DGNST01L   AI_DGNST_DTTM
--        T_ITSE_ANNT01L             INFO_CRET_DTTM
--        T_ITSE_LBLL01L             INFO_CRET_DTTM
--        T_ITSE_SNSH_GTHR01L        STRT_DTTM
--
--   3. 테이블스페이스가 TS_AIMS_DATA -> TS_AIMS_HIST_DATA / _IDX 로 바뀐다
--      AIMS_DEV 의 동종 파티션 이력 테이블(T_ITSE_AI_BRDW_JDG01L 등)이 쓰는
--      곳이다. 되돌리려면 아래 DEFINE 두 줄만 TS_AIMS_DATA / TS_AIMS_IDX 로
--      고치면 된다.
--
-- === 바꾸지 않는 것 ===
--   컬럼 구성·순서·자료형, 인덱스 이름(PK_T_ITSE_* 유지), 데이터.
--   보조 인덱스는 원래 하나도 없었으므로 새로 만들지 않는다.
--
-- === 관례 출처 ===
--   AIMS_DEV.T_ITSE_AI_BRDW_JDG01L 의 DBMS_METADATA.GET_DDL 실측.
--   월 단위 RANGE, 이름 P<YYYYMM> + PMAX, 로컬 인덱스, HIST 테이블스페이스.
--   기존 데이터가 전부 2026/08 이라 P202608 에 들어간다.
--
-- === 실패 시 ===
--   각 테이블의 백업 T_..._BAK 이 남는다. 말미의 DROP 은 실행하지 않고
--   안내만 하므로, 검증이 끝난 뒤 직접 지우면 된다.

DEFINE TBS_DATA = "TS_AIMS_HIST_DATA"
DEFINE TBS_IDX  = "TS_AIMS_HIST_IDX"

SET LINESIZE 300
SET PAGESIZE 200
SET TRIMSPOOL ON
SET SERVEROUTPUT ON

SPOOL 15_aimsc_hist_rebuild.log

PROMPT === 시작 시각 / 접속 계정 ===
SELECT USER AS connected_user, SYSDATE AS started_at FROM DUAL;

PROMPT
PROMPT === 재구축 전 건수 (말미의 대조에 쓴다) ===
SELECT 'T_ITSE_AI_DGNST01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_AI_DGNST01L;
SELECT 'T_ITSE_AI_DRF_DGNST01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_AI_DRF_DGNST01L;
SELECT 'T_ITSE_AI_MODL_OP01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_AI_MODL_OP01L;
SELECT 'T_ITSE_AI_MVPCT_DGNST01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_AI_MVPCT_DGNST01L;
SELECT 'T_ITSE_ANNT01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_ANNT01L;
SELECT 'T_ITSE_LBLL01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_LBLL01L;
SELECT 'T_ITSE_SNSH_GTHR01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_SNSH_GTHR01L;
SELECT 'T_ITSE_SNSH_PRPG01L' AS tab, COUNT(*) AS rows_before FROM T_ITSE_SNSH_PRPG01L;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_AI_DGNST01L
PROMPT   파티션 키 STRT_DTTM   /   PK (AI_DGNST_ID, STRT_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_AI_DGNST01L_BAK AS SELECT * FROM T_ITSE_AI_DGNST01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_AI_DGNST01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_AI_DGNST01L
(
    "AI_DGNST_ID"                VARCHAR2(36)   NOT NULL,
    "STRT_DTTM"                  DATE           NOT NULL,
    "END_DTTM"                   DATE           NOT NULL,
    "AI_DGNST_RSLT_CD"           VARCHAR2(2)    NOT NULL,
    "FILE_PATH"                  VARCHAR2(2000) NOT NULL
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("STRT_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_AI_DGNST01L" ON T_ITSE_AI_DGNST01L ("AI_DGNST_ID", "STRT_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_AI_DGNST01L ADD CONSTRAINT "PK_T_ITSE_AI_DGNST01L" PRIMARY KEY ("AI_DGNST_ID", "STRT_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_AI_DGNST01L ("AI_DGNST_ID", "STRT_DTTM", "END_DTTM", "AI_DGNST_RSLT_CD", "FILE_PATH") SELECT "AI_DGNST_ID", "STRT_DTTM", "END_DTTM", "AI_DGNST_RSLT_CD", "FILE_PATH" FROM T_ITSE_AI_DGNST01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_AI_DRF_DGNST01L
PROMPT   파티션 키 AI_DGNST_DTTM   /   PK (AI_DRF_DGNST_ID, AI_DGNST_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_AI_DRF_DGNST01L_BAK AS SELECT * FROM T_ITSE_AI_DRF_DGNST01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_AI_DRF_DGNST01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_AI_DRF_DGNST01L
(
    "AI_DRF_DGNST_ID"            VARCHAR2(36)   NOT NULL,
    "AI_DGNST_DTTM"              DATE           NOT NULL,
    "JDG_NRML_YN"                VARCHAR2(1),
    "DRF_ERR_CTNT"               VARCHAR2(1000),
    "AI_DGNST_ID"                VARCHAR2(36)   NOT NULL,
    "CCTV_ID"                    VARCHAR2(12)   NOT NULL,
    "DGNST_RSLT_FILE_PATH"       VARCHAR2(2000) NOT NULL,
    "DGNST_TRGT_IMG_FILE_PATH"   VARCHAR2(2000) NOT NULL,
    "DGNST_RLBLT_RT"             NUMBER(5,2)    NOT NULL,
    "EXMN_YN"                    CHAR(1)        NOT NULL,
    "FLPS_YN"                    VARCHAR2(1)
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("AI_DGNST_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_AI_DRF_DGNST01L" ON T_ITSE_AI_DRF_DGNST01L ("AI_DRF_DGNST_ID", "AI_DGNST_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_AI_DRF_DGNST01L ADD CONSTRAINT "PK_T_ITSE_AI_DRF_DGNST01L" PRIMARY KEY ("AI_DRF_DGNST_ID", "AI_DGNST_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_AI_DRF_DGNST01L ("AI_DRF_DGNST_ID", "AI_DGNST_DTTM", "JDG_NRML_YN", "DRF_ERR_CTNT", "AI_DGNST_ID", "CCTV_ID", "DGNST_RSLT_FILE_PATH", "DGNST_TRGT_IMG_FILE_PATH", "DGNST_RLBLT_RT", "EXMN_YN", "FLPS_YN") SELECT "AI_DRF_DGNST_ID", "AI_DGNST_DTTM", "JDG_NRML_YN", "DRF_ERR_CTNT", "AI_DGNST_ID", "CCTV_ID", "DGNST_RSLT_FILE_PATH", "DGNST_TRGT_IMG_FILE_PATH", "DGNST_RLBLT_RT", "EXMN_YN", "FLPS_YN" FROM T_ITSE_AI_DRF_DGNST01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_AI_MODL_OP01L
PROMPT   파티션 키 MNTG_STRT_DTTM   /   PK (AI_MODL_OP_ID, MNTG_STRT_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_AI_MODL_OP01L_BAK AS SELECT * FROM T_ITSE_AI_MODL_OP01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_AI_MODL_OP01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_AI_MODL_OP01L
(
    "AI_MODL_OP_ID"              VARCHAR2(36)   NOT NULL,
    "AI_MODL_ID"                 VARCHAR2(36)   NOT NULL,
    "EQPM_TYPE_NM"               VARCHAR2(100),
    "MNTG_ITM_NM"                VARCHAR2(100),
    "AI_MODL_USE_OBJTV_CTNT"     VARCHAR2(1000),
    "MNTG_STRT_DTTM"             DATE           NOT NULL,
    "MNTG_END_DTTM"              DATE,
    "AI_MODL_OP_STAT_CD"         VARCHAR2(2),
    "DGNST_PRFM_STAT_NM"         VARCHAR2(100),
    "TRNG_STRT_DTTM"             DATE,
    "TRNG_END_DTTM"              DATE,
    "DATST_ID"                   VARCHAR2(36)   NOT NULL
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("MNTG_STRT_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_AI_MODL_OP01L" ON T_ITSE_AI_MODL_OP01L ("AI_MODL_OP_ID", "MNTG_STRT_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_AI_MODL_OP01L ADD CONSTRAINT "PK_T_ITSE_AI_MODL_OP01L" PRIMARY KEY ("AI_MODL_OP_ID", "MNTG_STRT_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_AI_MODL_OP01L ("AI_MODL_OP_ID", "AI_MODL_ID", "EQPM_TYPE_NM", "MNTG_ITM_NM", "AI_MODL_USE_OBJTV_CTNT", "MNTG_STRT_DTTM", "MNTG_END_DTTM", "AI_MODL_OP_STAT_CD", "DGNST_PRFM_STAT_NM", "TRNG_STRT_DTTM", "TRNG_END_DTTM", "DATST_ID") SELECT "AI_MODL_OP_ID", "AI_MODL_ID", "EQPM_TYPE_NM", "MNTG_ITM_NM", "AI_MODL_USE_OBJTV_CTNT", "MNTG_STRT_DTTM", "MNTG_END_DTTM", "AI_MODL_OP_STAT_CD", "DGNST_PRFM_STAT_NM", "TRNG_STRT_DTTM", "TRNG_END_DTTM", "DATST_ID" FROM T_ITSE_AI_MODL_OP01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_AI_MVPCT_DGNST01L
PROMPT   파티션 키 AI_DGNST_DTTM   /   PK (AI_MVPCT_DGNST_ID, AI_DGNST_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_AI_MVPCT_DGNST01L_BAK AS SELECT * FROM T_ITSE_AI_MVPCT_DGNST01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_AI_MVPCT_DGNST01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_AI_MVPCT_DGNST01L
(
    "AI_MVPCT_DGNST_ID"          VARCHAR2(36)   NOT NULL,
    "AI_DGNST_DTTM"              DATE           NOT NULL,
    "JDG_NRML_YN"                VARCHAR2(1),
    "MVPCT_ERR_CTNT"             VARCHAR2(1000),
    "AI_DGNST_ID"                VARCHAR2(36)   NOT NULL,
    "CCTV_ID"                    VARCHAR2(12)   NOT NULL,
    "DGNST_RSLT_FILE_PATH"       VARCHAR2(2000) NOT NULL,
    "DGNST_TRGT_IMG_FILE_PATH"   VARCHAR2(2000) NOT NULL,
    "DGNST_RLBLT_RT"             NUMBER(5,2)    NOT NULL,
    "EXMN_YN"                    CHAR(1)        NOT NULL,
    "FLPS_YN"                    VARCHAR2(1)
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("AI_DGNST_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_AI_MVPCT_DGNST01L" ON T_ITSE_AI_MVPCT_DGNST01L ("AI_MVPCT_DGNST_ID", "AI_DGNST_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_AI_MVPCT_DGNST01L ADD CONSTRAINT "PK_T_ITSE_AI_MVPCT_DGNST01L" PRIMARY KEY ("AI_MVPCT_DGNST_ID", "AI_DGNST_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_AI_MVPCT_DGNST01L ("AI_MVPCT_DGNST_ID", "AI_DGNST_DTTM", "JDG_NRML_YN", "MVPCT_ERR_CTNT", "AI_DGNST_ID", "CCTV_ID", "DGNST_RSLT_FILE_PATH", "DGNST_TRGT_IMG_FILE_PATH", "DGNST_RLBLT_RT", "EXMN_YN", "FLPS_YN") SELECT "AI_MVPCT_DGNST_ID", "AI_DGNST_DTTM", "JDG_NRML_YN", "MVPCT_ERR_CTNT", "AI_DGNST_ID", "CCTV_ID", "DGNST_RSLT_FILE_PATH", "DGNST_TRGT_IMG_FILE_PATH", "DGNST_RLBLT_RT", "EXMN_YN", "FLPS_YN" FROM T_ITSE_AI_MVPCT_DGNST01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_ANNT01L
PROMPT   파티션 키 INFO_CRET_DTTM   /   PK (ANNT_ID, INFO_CRET_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_ANNT01L_BAK AS SELECT * FROM T_ITSE_ANNT01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_ANNT01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_ANNT01L
(
    "ANNT_ID"                    VARCHAR2(36)   NOT NULL,
    "INFO_CRET_DTTM"             DATE           NOT NULL,
    "INFO_UPDT_DTTM"             DATE,
    "FILE_PATH"                  VARCHAR2(2000),
    "FILE_NM"                    VARCHAR2(500),
    "FILE_DEL_YN"                VARCHAR2(1),
    "PRPG_ID"                    VARCHAR2(36)   NOT NULL
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("INFO_CRET_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_ANNT01L" ON T_ITSE_ANNT01L ("ANNT_ID", "INFO_CRET_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_ANNT01L ADD CONSTRAINT "PK_T_ITSE_ANNT01L" PRIMARY KEY ("ANNT_ID", "INFO_CRET_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_ANNT01L ("ANNT_ID", "INFO_CRET_DTTM", "INFO_UPDT_DTTM", "FILE_PATH", "FILE_NM", "FILE_DEL_YN", "PRPG_ID") SELECT "ANNT_ID", "INFO_CRET_DTTM", "INFO_UPDT_DTTM", "FILE_PATH", "FILE_NM", "FILE_DEL_YN", "PRPG_ID" FROM T_ITSE_ANNT01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_LBLL01L
PROMPT   파티션 키 INFO_CRET_DTTM   /   PK (LBLL_ID, INFO_CRET_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_LBLL01L_BAK AS SELECT * FROM T_ITSE_LBLL01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_LBLL01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_LBLL01L
(
    "LBLL_ID"                    VARCHAR2(36)   NOT NULL,
    "INFO_CRET_DTTM"             DATE           NOT NULL,
    "INFO_UPDT_DTTM"             DATE,
    "FILE_PATH"                  VARCHAR2(2000),
    "FILE_NM"                    VARCHAR2(500),
    "FILE_DEL_YN"                VARCHAR2(1),
    "PRPG_ID"                    VARCHAR2(36)   NOT NULL
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("INFO_CRET_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_LBLL01L" ON T_ITSE_LBLL01L ("LBLL_ID", "INFO_CRET_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_LBLL01L ADD CONSTRAINT "PK_T_ITSE_LBLL01L" PRIMARY KEY ("LBLL_ID", "INFO_CRET_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_LBLL01L ("LBLL_ID", "INFO_CRET_DTTM", "INFO_UPDT_DTTM", "FILE_PATH", "FILE_NM", "FILE_DEL_YN", "PRPG_ID") SELECT "LBLL_ID", "INFO_CRET_DTTM", "INFO_UPDT_DTTM", "FILE_PATH", "FILE_NM", "FILE_DEL_YN", "PRPG_ID" FROM T_ITSE_LBLL01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_SNSH_GTHR01L
PROMPT   파티션 키 STRT_DTTM   /   PK (SNSH_GTHR_ID, STRT_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_SNSH_GTHR01L_BAK AS SELECT * FROM T_ITSE_SNSH_GTHR01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_SNSH_GTHR01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_SNSH_GTHR01L
(
    "SNSH_GTHR_ID"               VARCHAR2(36)   NOT NULL,
    "STRT_DTTM"                  DATE           NOT NULL,
    "END_DTTM"                   DATE,
    "FILE_PATH"                  VARCHAR2(2000),
    "FILE_CNT"                   NUMBER(10,0),
    "PRPG_YN"                    VARCHAR2(1),
    "AI_DGNST_YN"                VARCHAR2(1)
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("STRT_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_SNSH_GTHR01L" ON T_ITSE_SNSH_GTHR01L ("SNSH_GTHR_ID", "STRT_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_SNSH_GTHR01L ADD CONSTRAINT "PK_T_ITSE_SNSH_GTHR01L" PRIMARY KEY ("SNSH_GTHR_ID", "STRT_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_SNSH_GTHR01L ("SNSH_GTHR_ID", "STRT_DTTM", "END_DTTM", "FILE_PATH", "FILE_CNT", "PRPG_YN", "AI_DGNST_YN") SELECT "SNSH_GTHR_ID", "STRT_DTTM", "END_DTTM", "FILE_PATH", "FILE_CNT", "PRPG_YN", "AI_DGNST_YN" FROM T_ITSE_SNSH_GTHR01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT T_ITSE_SNSH_PRPG01L
PROMPT   파티션 키 PRPG_STRT_DTTM   /   PK (PRPG_ID, PRPG_STRT_DTTM)
PROMPT ================================================================

-- (1) 데이터 백업. 제약·인덱스는 복사되지 않으므로 이름 충돌이 없다.
CREATE TABLE T_ITSE_SNSH_PRPG01L_BAK AS SELECT * FROM T_ITSE_SNSH_PRPG01L;

-- (2) 원본 제거. PK 제약과 인덱스도 함께 사라진다.
DROP TABLE T_ITSE_SNSH_PRPG01L;

-- (3) 파티션 테이블로 재생성
CREATE TABLE T_ITSE_SNSH_PRPG01L
(
    "PRPG_ID"                    VARCHAR2(36)   NOT NULL,
    "PRPG_STRT_DTTM"             DATE           NOT NULL,
    "PRPG_END_DTTM"              DATE           NOT NULL,
    "PRPG_PRGS_RSLT_CD"          VARCHAR2(2)    NOT NULL
)
TABLESPACE &TBS_DATA
PARTITION BY RANGE("PRPG_STRT_DTTM")
(
    PARTITION "P202608" VALUES LESS THAN (TO_DATE('20260901','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "P202609" VALUES LESS THAN (TO_DATE('20261001','YYYYMMDD')) TABLESPACE &TBS_DATA,
    PARTITION "PMAX" VALUES LESS THAN (MAXVALUE) TABLESPACE &TBS_DATA
);

-- (4) PK — 로컬 유니크 인덱스를 먼저 만들고 제약조건이 그것을 쓰게 한다
CREATE UNIQUE INDEX "PK_T_ITSE_SNSH_PRPG01L" ON T_ITSE_SNSH_PRPG01L ("PRPG_ID", "PRPG_STRT_DTTM")
    TABLESPACE &TBS_IDX LOCAL
(
    PARTITION "P202608" TABLESPACE &TBS_IDX,
    PARTITION "P202609" TABLESPACE &TBS_IDX,
    PARTITION "PMAX" TABLESPACE &TBS_IDX
);

ALTER TABLE T_ITSE_SNSH_PRPG01L ADD CONSTRAINT "PK_T_ITSE_SNSH_PRPG01L" PRIMARY KEY ("PRPG_ID", "PRPG_STRT_DTTM");

-- (5) 데이터 복원
INSERT INTO T_ITSE_SNSH_PRPG01L ("PRPG_ID", "PRPG_STRT_DTTM", "PRPG_END_DTTM", "PRPG_PRGS_RSLT_CD") SELECT "PRPG_ID", "PRPG_STRT_DTTM", "PRPG_END_DTTM", "PRPG_PRGS_RSLT_CD" FROM T_ITSE_SNSH_PRPG01L_BAK;
COMMIT;

PROMPT
PROMPT ================================================================
PROMPT 검증
PROMPT ================================================================
PROMPT -- 건수: 백업본과의 차이가 전부 0 이어야 한다
SELECT 'T_ITSE_AI_DGNST01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_AI_DGNST01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_AI_DGNST01L) - (SELECT COUNT(*) FROM T_ITSE_AI_DGNST01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_AI_DRF_DGNST01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_AI_DRF_DGNST01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_AI_DRF_DGNST01L) - (SELECT COUNT(*) FROM T_ITSE_AI_DRF_DGNST01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_AI_MODL_OP01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_AI_MODL_OP01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_AI_MODL_OP01L) - (SELECT COUNT(*) FROM T_ITSE_AI_MODL_OP01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_AI_MVPCT_DGNST01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_AI_MVPCT_DGNST01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_AI_MVPCT_DGNST01L) - (SELECT COUNT(*) FROM T_ITSE_AI_MVPCT_DGNST01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_ANNT01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_ANNT01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_ANNT01L) - (SELECT COUNT(*) FROM T_ITSE_ANNT01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_LBLL01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_LBLL01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_LBLL01L) - (SELECT COUNT(*) FROM T_ITSE_LBLL01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_SNSH_GTHR01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_SNSH_GTHR01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_SNSH_GTHR01L) - (SELECT COUNT(*) FROM T_ITSE_SNSH_GTHR01L_BAK) AS diff FROM DUAL;
SELECT 'T_ITSE_SNSH_PRPG01L' AS tab, (SELECT COUNT(*) FROM T_ITSE_SNSH_PRPG01L) AS rows_after, (SELECT COUNT(*) FROM T_ITSE_SNSH_PRPG01L) - (SELECT COUNT(*) FROM T_ITSE_SNSH_PRPG01L_BAK) AS diff FROM DUAL;

PROMPT
PROMPT -- 인덱스: 8개 전부 PARTITIONED='YES' / UNIQUENESS='UNIQUE' 여야 한다
COL table_name FORMAT A28
COL index_name FORMAT A30
COL uniqueness FORMAT A10
COL partitioned FORMAT A11
COL tablespace_name FORMAT A20
SELECT table_name, index_name, uniqueness, partitioned, tablespace_name
  FROM all_indexes WHERE table_owner='AIMSC_DEV' AND table_name LIKE '%01L'
 ORDER BY table_name;

PROMPT
PROMPT -- 파티션: 8개 x 3 (P202608 / P202609 / PMAX)
COL partitioning_type FORMAT A10
SELECT table_name, partitioning_type, partition_count
  FROM all_part_tables WHERE owner='AIMSC_DEV' ORDER BY table_name;

PROMPT
PROMPT -- 파티션 키
COL name FORMAT A28
COL column_name FORMAT A24
SELECT name, column_name, column_position
  FROM all_part_key_columns WHERE owner='AIMSC_DEV' ORDER BY name, column_position;

PROMPT
PROMPT -- PK 제약: ENABLED / VALIDATED
COL constraint_name FORMAT A30
COL status FORMAT A10
COL validated FORMAT A14
SELECT table_name, constraint_name, status, validated
  FROM all_constraints
 WHERE owner='AIMSC_DEV' AND constraint_type='P' AND table_name LIKE '%01L'
 ORDER BY table_name;

PROMPT
PROMPT -- 무효 객체 (0건이어야 한다)
SELECT object_type, object_name, status FROM all_objects
 WHERE owner='AIMSC_DEV' AND status <> 'VALID';

SPOOL OFF

PROMPT
PROMPT ================================================================
PROMPT 백업 테이블 정리
PROMPT   위 검증이 전부 통과한 뒤에 아래를 직접 실행할 것.
PROMPT   자동으로 지우지 않는 이유: 문제가 생겼을 때 되돌릴 유일한 수단이다.
PROMPT ================================================================
PROMPT   DROP TABLE T_ITSE_AI_DGNST01L_BAK;
PROMPT   DROP TABLE T_ITSE_AI_DRF_DGNST01L_BAK;
PROMPT   DROP TABLE T_ITSE_AI_MODL_OP01L_BAK;
PROMPT   DROP TABLE T_ITSE_AI_MVPCT_DGNST01L_BAK;
PROMPT   DROP TABLE T_ITSE_ANNT01L_BAK;
PROMPT   DROP TABLE T_ITSE_LBLL01L_BAK;
PROMPT   DROP TABLE T_ITSE_SNSH_GTHR01L_BAK;
PROMPT   DROP TABLE T_ITSE_SNSH_PRPG01L_BAK;
PROMPT
PROMPT 다음: T_ITSE_CCTV_01M 시노님 추가 -> 16_aimsc_synonym.sql

-- tbsql 이 SQL> 프롬프트에서 대기하지 않도록 반드시 종료한다.
EXIT;
